# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: sc-tsa-dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'npm install and build'
  
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
#   containerRegistry: 'JFrog Artifactory Test'
    repository: 'docker-stg.artifactory.global.standardchartered.com/test-docker-azure/$(imageName)'
    Dockerfile: '**/Dockerfile'
    command: 'build'
    tags: 'latest'
      
- task: ArtifactoryDocker@1
      displayName: 'Push Docker Image to Jfrog'
      inputs:
        command: 'push'
        artifactoryService: 'JFrog Artifactory Test'
        targetRepo: 'test-docker-azure'
        imageName: 'docker-stg.artifactory.global.standardchartered.com/test-docker-azure/pipelines-javascript-docker:latest'
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'


- task: ArtifactoryPublishBuildInfo@1
      displayName: 'Publish Artifact Build Info'
      inputs:
        artifactoryService: 'JFrog Artifactory Test'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
